### ISSUE TITLE
Error while inserting Vcard object

### ISSUE THREAD

**Issue by aarsy** [mangstadt/ez-vcard-android#2]
Gives the below error sometimes and doesn't give this error sometime but the contact cannot be inserted in the phone
<br>
01-04 16:01:56.188 3358-14110/? E/ContentProviderOperation: mType: 1, mUri: content://com.android.contacts/data, mSelection: null, mExpectedCount: null, mYieldAllowed: false, mValues: data1=Aakash2 data2=Aakash2 mimetype=vnd.android.cursor.item/name, mValuesBackReferences: raw_contact_id=0, mSelectionArgsBackReferences: null
<br> E/JavaBinder: *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
                                              java.lang.ArrayIndexOutOfBoundsException: asked for back ref 0 but there are only 0 back refs
                                                  at android.content.ContentProviderOperation.backRefToValue(ContentProviderOperation.java:393)
                                                  at android.content.ContentProviderOperation.resolveValueBackReferences(ContentProviderOperation.java:333)
                                                  at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:240)
                                                  at com.android.providers.contacts.AbstractContactsProvider.applyBatch(AbstractContactsProvider.java:240)
                                                  at com.android.providers.contacts.ContactsProvider2.applyBatch(ContactsProvider2.java:3531)
                                                  at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:301)
                                                  at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:192)
                                                  at android.os.Binder.execTransact(Binder.java:446)

**Comment by mangstadt** [comment]
Sorry, don't know.  Looks like an Android issue.

**Comment by aarsy** [comment]
I have solved the issue..There was some error in you code. I shall create a
pull request after updating it.
